# Generated by Django 5.2.8 on 2025-11-21 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rider',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rider',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
